/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package dev.argon.jawawasm.app;

import dev.argon.jawawasm.app.wast.WastLoader;

import java.io.PrintWriter;
import java.nio.file.Path;

/**
 * App for executing wast scripts.
 * Requires the wasm spec interpreter to convert text format to binary.
 */
public class App {
	App() {}

	/**
	 * Execute wast scripts.
	 * @param args Command line arguments.
	 * @throws Throwable if an error occurs.
	 *
	 */
    public static void main(String[] args) throws Throwable {
		String scriptFile = args[0];

		String wasmToolsExecutableStr = System.getenv("JAWAWASM_WASM_TOOLS_PATH");
		Path wasmToolsExecutable = Path.of(wasmToolsExecutableStr);

		System.out.println("Reading script");
		var loader = new WastLoader(wasmToolsExecutable);

		try(var scriptLoaded = loader.loadScript(Path.of(scriptFile))) {
			System.out.println("Executing script");

			@SuppressWarnings("DefaultCharset")
			var output = new PrintWriter(System.out);

			try(var interpreter = new ScriptInterpreter(loader, output)) {
				interpreter.initialize();
				interpreter.executeScript(scriptLoaded);
			}

		}
    }
}
