/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package dev.argon.jawawasm.app;

import dev.argon.jawawasm.format.text.ScriptCommand;
import dev.argon.jawawasm.format.text.ScriptCommandInfo;
import dev.argon.jawawasm.format.text.ScriptReader;

import java.io.PrintWriter;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.List;

/**
 * App for executing wast scripts.
 * Requires the wasm spec interpreter to convert text format to binary.
 */
public class App {
	App() {}

	/**
	 * Execute wast scripts.
	 * @param args Command line arguments.
	 * @throws Throwable if an error occurs.
	 *
	 */
    public static void main(String[] args) throws Throwable {
		String scriptFile = args[0];

		String wasmExecutableStr = System.getenv("JAWAWASM_WASM_PATH");
		Path wasmExecutable = Path.of(wasmExecutableStr);

		List<? extends ScriptCommandInfo> commands;
		System.out.println("Reading module");
		try(var reader = Files.newBufferedReader(Path.of(scriptFile))) {
			commands = new ScriptReader(reader).readCommands();
		}

		System.out.println("Executing script");

		@SuppressWarnings("DefaultCharset")
		var output = new PrintWriter(System.out);

		try(var interpreter = new ScriptInterpreter(wasmExecutable, output)) {
			interpreter.executeScript(scriptFile, commands);
		}
    }
}
