package dev.argon.jawawasm.engine.compiler;

/**
 * A resource file generated by the WebAssembly compiler.
 */
public non-sealed abstract class WasmResourceGenerator implements WasmOutputGenerator {
	WasmResourceGenerator() {}

	public abstract String resourceName();
	public abstract byte[] generate();
}
