package dev.argon.jawawasm.engine.compiler;

import dev.argon.jawawasm.runtime.ModuleLinkException;
import dev.argon.jawawasm.runtime.ModuleResolutionException;

import java.lang.classfile.ClassHierarchyResolver;
import java.lang.constant.ClassDesc;

/**
 * Generator for a class from WebAssembly input.
 */
public abstract non-sealed class WasmClassGenerator implements WasmOutputGenerator {
	WasmClassGenerator(ModuleCompiler compiler) {
		this.compiler = compiler;
	}

	final ModuleCompiler compiler;

	/**
	 * Gets the descriptor for the class.
	 * @return The descriptor.
	 */
	public abstract ClassDesc className();

	/**
	 * Gets base class information from this generator.
	 * @return The class hierarchy info for this generator.
	 */
	public abstract ClassHierarchyResolver.ClassHierarchyInfo hierarchyInfo();

	/**
	 * Generates the class.
	 * @return The generated bytecode.
	 * @throws ModuleResolutionException If a referenced module cannot be found.
	 */
	public final byte[] generate() {
		return generateImpl();
	}

	abstract byte[] generateImpl();
}
