package dev.argon.jawawasm.engine.compiler;

import dev.argon.jawawasm.runtime.ModuleResolutionException;

import java.lang.constant.ClassDesc;

/**
 * Generator for a class from WebAssembly input.
 */
public abstract class WasmClassGenerator {
	WasmClassGenerator(ModuleCompiler compiler) {
		this.compiler = compiler;
	}

	final ModuleCompiler compiler;

	/**
	 * Gets the descriptor for the class.
	 * @return The descriptor.
	 */
	public abstract ClassDesc className();

	/**
	 * Generates the class.
	 * @return The generated bytecode.
	 * @throws ModuleResolutionException If a referenced module cannot be found.
	 */
	public final byte[] generate() throws ModuleResolutionException {
		byte[] bc = generateImpl();



//		ClassModel classModel = ClassFile.of().parse(bc);
//		Path p = Path.of("classes/" + classModel.thisClass().asInternalName() + ".class");
//		try {
//			Files.createDirectories(p.getParent());
//			Files.write(p, bc);
//		} catch(IOException e) {
//			throw new RuntimeException(e);
//		}

//		System.err.println(classModel);
//		for (MethodModel method : classModel.methods()) {
//			System.err.println(method);
//			method.code().ifPresent(codeModel -> {
//				System.err.println("Instructions for " + method.methodName().stringValue() + ":");
//				codeModel.elementList().forEach(System.err::println);
//			});
//		}
//		System.err.println(Base64.getEncoder().encodeToString(bc));

		return bc;
	}

	abstract byte[] generateImpl() throws ModuleResolutionException;
}
