/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("jvmwasm.java-library-conventions")
}

dependencies {
    api(project(":format"))
    implementation("org.ow2.asm:asm:9.4")
    implementation("org.ow2.asm:asm-commons:9.4")
}
