/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("jawawasm.java-library-conventions")
    `maven-publish`
    signing
}


dependencies {
    api(project(":format"))
}

publishing {
    publications {
        create<MavenPublication>("mavenJava") {
            artifactId = "wasm-engine"
            from(components["java"])
        }
    }
}

signing {
    sign(publishing.publications["mavenJava"])
}
