/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("jawawasm.java-application-conventions")
}

dependencies {
    implementation(project(":format"))
    implementation(project(":engine"))

    testImplementation("org.junit.jupiter:junit-jupiter:5.9.2")
    testRuntimeOnly("org.junit.platform:junit-platform-launcher")
}

application {
    // Define the main class for the application.
    mainClass.set("dev.argon.jawawasm.app.App")
}

