/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("jvmwasm.java-application-conventions")
}

dependencies {
    implementation(project(":format"))
    implementation(project(":engine"))
}

application {
    // Define the main class for the application.
    mainClass.set("jvmwasm.app.App")
}

