/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package dev.argon.jawawasm.app;

import dev.argon.jawawasm.app.wast.WastLoader;
import org.junit.jupiter.api.Disabled;

import java.io.PrintWriter;
import java.nio.file.Path;

class ScriptTestsInterpreter extends ScriptTestsBase {

	@Override
	protected ScriptExecutor<?> createScriptExecutor(WastLoader loader) {
		return new ScriptInterpreter(loader, new PrintWriter(System.out));
	}
}
