/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package dev.argon.jawawasm.app;

import org.junit.jupiter.api.Disabled;

import java.io.PrintWriter;
import java.nio.file.Path;

class ScriptTestsInterpreter extends ScriptTestsBase {

	@Override
	protected ScriptExecutor<?> createScriptExecutor(Path wasmExecutable) {
		return new ScriptInterpreter(wasmExecutable, new PrintWriter(System.out));
	}
}
