/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package dev.argon.jawawasm.app;

import dev.argon.jawawasm.format.text.ScriptCommand;
import dev.argon.jawawasm.format.text.ScriptCommandInfo;
import dev.argon.jawawasm.format.text.ScriptReader;
import org.junit.jupiter.api.DynamicTest;
import org.junit.jupiter.api.TestFactory;

import java.io.IOException;
import java.io.PrintWriter;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.Arrays;
import java.util.List;
import java.util.Set;
import java.util.stream.Stream;

import static org.junit.jupiter.api.Assertions.assertEquals;

class ScriptTests {

	private final List<String> excludedTests = List.of(new String[] {
		"inline-module.wast",

		// Exceptions
//		"try_table.wast",
//		"exports.wast",
//		"instance.wast",

		// Memory64
		"table_fill.wast",
		"memory_copy.wast",
		"memory_fill.wast",
		"memory64.wast",
		"memory_grow64.wast",

		// ref types and ref type functions
		"tag.wast",
		"ref.wast",
		"elem.wast",
		"type-equivalence.wast",


		"gc/",
		"relaxed-simd/",
		"multi-memory/",

		"simd/simd_memory-multi.wast",
	});

	private static final String testDir = "../webassembly-spec/test/core";

    @TestFactory
	Stream<DynamicTest> wastScriptTests() throws IOException {
		var testPath = Path.of(testDir);
		return Files.walk(testPath)
				.filter(path -> Files.isRegularFile(path) && path.getFileName().toString().endsWith(".wast") && !isExcludedTest(testPath.relativize(path)))
				.map(path -> DynamicTest.dynamicTest(testPath.relativize(path).toString(), () -> runWastScript(path)));
	}

	private boolean isExcludedTest(Path path) {
		if(excludedTests.contains(path.toString().replace('\\', '/'))) {
			return true;
		}

		var parent = path.getParent();
		if(parent != null) {
			if(excludedTests.contains(parent.toString().replace('\\', '/') + "/")) {
				return true;
			}
		}

//		if(!path.toString().equals("align.wast")) {
//			return true;
//		}

		return false;
	}

	private void runWastScript(Path path) throws Throwable {
		List<? extends ScriptCommandInfo> commands;
		try(var reader = Files.newBufferedReader(path)) {
			commands = new ScriptReader(reader).readCommands();
		}

		String wasmPathStr = System.getenv("JAWAWASM_WASM_PATH");
		if(wasmPathStr == null) {
			wasmPathStr = "../webassembly-spec/interpreter/wasm";
		}

		try(var interpreter = new ScriptInterpreter(Path.of(wasmPathStr), new PrintWriter(System.out))) {
			interpreter.executeScript(path.getFileName().toString(), commands);
		}
	}
}
