/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package dev.argon.jawawasm.app;

import java.io.PrintWriter;
import java.nio.file.Path;
import java.util.concurrent.atomic.AtomicInteger;

class ScriptTestsClassLoader extends ScriptTestsBase {

	private final AtomicInteger testNum = new AtomicInteger(0);

	@Override
	protected ScriptExecutor<?> createScriptExecutor(Path wasmExecutable) {
		int n = testNum.getAndIncrement();
		return new ScriptReflectionExecutor("dev.argon.jawawasm.test.testscript" + n, wasmExecutable, new PrintWriter(System.out));
	}
}
