/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package dev.argon.jawawasm.app;

import dev.argon.jawawasm.format.text.ScriptCommand;
import dev.argon.jawawasm.format.text.ScriptCommandInfo;
import dev.argon.jawawasm.format.text.ScriptReader;
import org.junit.jupiter.api.DynamicTest;
import org.junit.jupiter.api.TestFactory;
import org.junit.jupiter.api.parallel.Execution;
import org.junit.jupiter.api.parallel.ExecutionMode;

import java.io.File;
import java.io.IOException;
import java.io.PrintWriter;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.Arrays;
import java.util.List;
import java.util.Set;
import java.util.stream.Stream;

import static org.junit.jupiter.api.Assertions.assertEquals;

@Execution(ExecutionMode.CONCURRENT)
class ScriptTests {

	private final List<String> excludedTests = List.of(new String[] {
		// Exclude tests for the text format.
		"id.wast",
		"annotations.wast",
		"inline-module.wast",

	});

	private static final String testDir = "../webassembly-spec/test/core";

    @TestFactory
	Stream<DynamicTest> wastScriptTests() throws IOException {
		var testPath = Path.of(testDir);
		return Files.walk(testPath)
				.filter(path -> Files.isRegularFile(path) && path.getFileName().toString().endsWith(".wast") && !isExcludedTest(testPath.relativize(path)))
				.map(path -> DynamicTest.dynamicTest(testPath.relativize(path).toString(), () -> runWastScript(path)));
	}

	private boolean isExcludedTest(Path path) {
		if(excludedTests.contains(path.toString().replace('\\', '/'))) {
			return true;
		}

		var parent = path.getParent();
		if(parent != null) {
			if(excludedTests.contains(parent.toString().replace(File.pathSeparator, "/") + "/")) {
				return true;
			}
		}

//		if(!path.toString().equals("type-subtyping.wast")) {
//			return true;
//		}

		return false;
	}

	private void runWastScript(Path path) throws Throwable {
		List<? extends ScriptCommandInfo> commands;
		try(var reader = Files.newBufferedReader(path)) {
			commands = new ScriptReader(reader).readCommands();
		}

		String wasmPathStr = System.getenv("JAWAWASM_WASM_PATH");
		if(wasmPathStr == null) {
			wasmPathStr = "../webassembly-spec/interpreter/wasm";
		}

		try(var interpreter = new ScriptInterpreter(Path.of(wasmPathStr), new PrintWriter(System.out))) {
			interpreter.executeScript(path.getFileName().toString(), commands);
		}
	}
}
