/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    // Apply the common convention plugin for shared build configuration between library and application projects.
    id("jvmwasm.java-common-conventions")

    // Apply the application plugin to add support for building a CLI application in Java.
    application
}

tasks.withType<JavaExec> {
    jvmArgs = listOf("-Xmx8192m")
}

