/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    // Apply the java Plugin to add support for Java.
    java
}

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
}

dependencies {
    compileOnly("org.jspecify:jspecify:0.3.0")
    testImplementation("org.junit.jupiter:junit-jupiter:5.9.1")
}


tasks.withType<JavaCompile> {
    options.compilerArgs.add("--enable-preview")
    options.release.set(19)
}

tasks.named<Test>("test") {
    useJUnitPlatform()
    jvmArgs(listOf("--enable-preview", "-Xmx8192m"))
    maxParallelForks = (Runtime.getRuntime().availableProcessors() / 2).takeIf { it > 0 } ?: 1
}

