/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package jvmwasm.app;

import jvmwasm.format.text.ScriptCommand;
import jvmwasm.format.text.ScriptReader;

import java.io.PrintWriter;
import java.io.Writer;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.List;

public class App {
    public static void main(String[] args) throws Throwable {
		String scriptFile = args[0];

		String wasmExecutableStr = System.getenv("JVMWASM_WASM_PATH");
		Path wasmExecutable = Path.of(wasmExecutableStr);

		List<? extends ScriptCommand> commands;
		System.out.println("Reading module");
		try(var reader = Files.newBufferedReader(Path.of(scriptFile))) {
			commands = new ScriptReader(reader).readCommands();
		}

		System.out.println("Executing script");
		try(var interpreter = new ScriptInterpreter(wasmExecutable, new PrintWriter(System.out))) {
			interpreter.executeScript(commands);
		}

    }
}
